name: ci - lint - files - *.json
on:
  push:
    branches: [ main ]
    paths: [ "**/*.json", "**/*.jsonc" ]
  pull_request:
    branches: [ main ]
    paths: [ "**/*.json", "**/*.jsonc" ]
jobs:
  json-lint:
    name: json lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: validate json files
        run: |
          find . -name '*.json' -not -path './.git/*' | while read f; do
            echo "Checking $f ..."
            python3 -m json.tool "$f" > /dev/null
          done
